// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlLiteDataAccess;

#nullable disable

namespace SqlLiteDataAccess.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20221228235848_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("MoneyEntity.Dto.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<string>("Table")
                        .HasColumnType("TEXT");

                    b.Property<long>("TgId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("telegram_id");

                    b.Property<string>("TgName")
                        .HasColumnType("TEXT")
                        .HasColumnName("telegram_name");

                    b.Property<string>("WalletCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("wallet_code");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("MoneyEntity.Dto.Bid", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("bid_id");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MineId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mine_id");

                    b.Property<string>("Table")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("MoneyEntity.Dto.Transfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("transfer_id");

                    b.Property<long?>("AccountFromId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_from_id");

                    b.Property<long?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("transfer_code");

                    b.Property<decimal>("CurrencyValue")
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_value");

                    b.Property<string>("Table")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransferTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("transfer_time");

                    b.HasKey("Id");

                    b.HasIndex("AccountFromId");

                    b.HasIndex("AccountId");

                    b.ToTable("transfers", (string)null);
                });

            modelBuilder.Entity("MoneyEntity.Dto.Bid", b =>
                {
                    b.HasOne("MoneyEntity.Dto.Account", "Account")
                        .WithMany("Bids")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MoneyEntity.Dto.Transfer", b =>
                {
                    b.HasOne("MoneyEntity.Dto.Account", "AccountFrom")
                        .WithMany("TransfersFrom")
                        .HasForeignKey("AccountFromId");

                    b.HasOne("MoneyEntity.Dto.Account", null)
                        .WithMany("TransfersTo")
                        .HasForeignKey("AccountId");

                    b.Navigation("AccountFrom");
                });

            modelBuilder.Entity("MoneyEntity.Dto.Account", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("TransfersFrom");

                    b.Navigation("TransfersTo");
                });
#pragma warning restore 612, 618
        }
    }
}
